NOTE_PROTOCOL_ENVELOPE_ID = "NOTE"

# 4d xx yy bytes
MAX_SCRIPT_ELEMENT_SIZE = 520
# 4c zz bytes
MAX_STANDARD_STACK_ITEM_SIZE = 80
MAX_DATA_SEGMENTS = 5

MAX_SCRIPT_FULL_SIZE = MAX_SCRIPT_ELEMENT_SIZE * MAX_DATA_SEGMENTS
MAX_STACK_FULL_SIZE = MAX_STANDARD_STACK_ITEM_SIZE * MAX_DATA_SEGMENTS

MAX_SEQUENCE = 0xffffffff
MAX_LOCKTIME = 0xffffffff